### ISSUE TITLE
Ubuntu 16.04?

### ISSUE THREAD

**Issue by ianneub** [dreamhost/veewee-definitions#97]
Howdy,

Do you guys have a version setup for Ubuntu 16.04 or did you switch to another build process?

**Comment by drwahl** [comment]
We've been getting our Ubuntu images directly from Canonical recently.  I'm happy to provide any insight I have though, if you are trying to build 16.04 and are running into issues.

**Comment by ianneub** [comment]
Thanks @drwahl ! I was exploring DreamCompute and trying to create my own image of Ubuntu 16.04 with all the current updates rolled in. I launched an instance on DC from the 16.04 image, ran the updates and then took an image from that. I wasn't able to login to SSH on subsequent VMs launched from that image. Not sure what is needed on 16.04 to get that to work right, so was hoping for something ready built that I could take a look at.

Do you happen to have any sample code for taking an image from Canonical and turning into something that openstack and DC can use?

I created an image from this in DC: http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-root.tar.gz but that didn't work of course. Maybe there are some easy steps to take to turn that into an image that DC can use?

**Comment by drwahl** [comment]
If you are simply looking for a base 16.04 image with updated packages, that's something I can (relatively) easily do for you (and something we need to do anyways...).  However, that doesn't directly answer your question.  DreamCompute uses ceph on the backend, which means it's using .raw images in the background.  While DreamCompute *can* accept non-raw images, uploading images in .raw is our current suggested method (otherwise, you have to issue a `glance task` to convert the image to raw after uploading).

One relatively simple way to customize the 16.04 image would be to download it (`glance image-download`), launch it with qemu, run `apt-get upgrade/dist-upgrade`, and then shut the VM down and re-upload the resulting qemu image.  There are other options, however, so if you would like to explore those options, let me know.

**Comment by ianneub** [comment]
Thanks @drwahl I'll give that a shot. The goal is an updated 16.04 image, however I thought I'd learn more about OpenStack in the process of getting to that point.

Thanks for your tips, I think that has got me in the right direction!
